// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"spoolman-go/ent/filament"
	"spoolman-go/ent/filamentfield"
	"spoolman-go/ent/predicate"
	"spoolman-go/ent/spool"
	"spoolman-go/ent/vendor"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FilamentQuery is the builder for querying Filament entities.
type FilamentQuery struct {
	config
	ctx        *QueryContext
	order      []filament.OrderOption
	inters     []Interceptor
	predicates []predicate.Filament
	withVendor *VendorQuery
	withSpools *SpoolQuery
	withExtra  *FilamentFieldQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FilamentQuery builder.
func (fq *FilamentQuery) Where(ps ...predicate.Filament) *FilamentQuery {
	fq.predicates = append(fq.predicates, ps...)
	return fq
}

// Limit the number of records to be returned by this query.
func (fq *FilamentQuery) Limit(limit int) *FilamentQuery {
	fq.ctx.Limit = &limit
	return fq
}

// Offset to start from.
func (fq *FilamentQuery) Offset(offset int) *FilamentQuery {
	fq.ctx.Offset = &offset
	return fq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fq *FilamentQuery) Unique(unique bool) *FilamentQuery {
	fq.ctx.Unique = &unique
	return fq
}

// Order specifies how the records should be ordered.
func (fq *FilamentQuery) Order(o ...filament.OrderOption) *FilamentQuery {
	fq.order = append(fq.order, o...)
	return fq
}

// QueryVendor chains the current query on the "vendor" edge.
func (fq *FilamentQuery) QueryVendor() *VendorQuery {
	query := (&VendorClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(filament.Table, filament.FieldID, selector),
			sqlgraph.To(vendor.Table, vendor.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, filament.VendorTable, filament.VendorColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySpools chains the current query on the "spools" edge.
func (fq *FilamentQuery) QuerySpools() *SpoolQuery {
	query := (&SpoolClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(filament.Table, filament.FieldID, selector),
			sqlgraph.To(spool.Table, spool.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, filament.SpoolsTable, filament.SpoolsColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExtra chains the current query on the "extra" edge.
func (fq *FilamentQuery) QueryExtra() *FilamentFieldQuery {
	query := (&FilamentFieldClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(filament.Table, filament.FieldID, selector),
			sqlgraph.To(filamentfield.Table, filamentfield.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, filament.ExtraTable, filament.ExtraColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Filament entity from the query.
// Returns a *NotFoundError when no Filament was found.
func (fq *FilamentQuery) First(ctx context.Context) (*Filament, error) {
	nodes, err := fq.Limit(1).All(setContextOp(ctx, fq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{filament.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fq *FilamentQuery) FirstX(ctx context.Context) *Filament {
	node, err := fq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Filament ID from the query.
// Returns a *NotFoundError when no Filament ID was found.
func (fq *FilamentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(1).IDs(setContextOp(ctx, fq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{filament.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fq *FilamentQuery) FirstIDX(ctx context.Context) int {
	id, err := fq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Filament entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Filament entity is found.
// Returns a *NotFoundError when no Filament entities are found.
func (fq *FilamentQuery) Only(ctx context.Context) (*Filament, error) {
	nodes, err := fq.Limit(2).All(setContextOp(ctx, fq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{filament.Label}
	default:
		return nil, &NotSingularError{filament.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fq *FilamentQuery) OnlyX(ctx context.Context) *Filament {
	node, err := fq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Filament ID in the query.
// Returns a *NotSingularError when more than one Filament ID is found.
// Returns a *NotFoundError when no entities are found.
func (fq *FilamentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(2).IDs(setContextOp(ctx, fq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{filament.Label}
	default:
		err = &NotSingularError{filament.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fq *FilamentQuery) OnlyIDX(ctx context.Context) int {
	id, err := fq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Filaments.
func (fq *FilamentQuery) All(ctx context.Context) ([]*Filament, error) {
	ctx = setContextOp(ctx, fq.ctx, ent.OpQueryAll)
	if err := fq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Filament, *FilamentQuery]()
	return withInterceptors[[]*Filament](ctx, fq, qr, fq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fq *FilamentQuery) AllX(ctx context.Context) []*Filament {
	nodes, err := fq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Filament IDs.
func (fq *FilamentQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fq.ctx.Unique == nil && fq.path != nil {
		fq.Unique(true)
	}
	ctx = setContextOp(ctx, fq.ctx, ent.OpQueryIDs)
	if err = fq.Select(filament.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fq *FilamentQuery) IDsX(ctx context.Context) []int {
	ids, err := fq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fq *FilamentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fq.ctx, ent.OpQueryCount)
	if err := fq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fq, querierCount[*FilamentQuery](), fq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fq *FilamentQuery) CountX(ctx context.Context) int {
	count, err := fq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fq *FilamentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fq.ctx, ent.OpQueryExist)
	switch _, err := fq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fq *FilamentQuery) ExistX(ctx context.Context) bool {
	exist, err := fq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FilamentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fq *FilamentQuery) Clone() *FilamentQuery {
	if fq == nil {
		return nil
	}
	return &FilamentQuery{
		config:     fq.config,
		ctx:        fq.ctx.Clone(),
		order:      append([]filament.OrderOption{}, fq.order...),
		inters:     append([]Interceptor{}, fq.inters...),
		predicates: append([]predicate.Filament{}, fq.predicates...),
		withVendor: fq.withVendor.Clone(),
		withSpools: fq.withSpools.Clone(),
		withExtra:  fq.withExtra.Clone(),
		// clone intermediate query.
		sql:  fq.sql.Clone(),
		path: fq.path,
	}
}

// WithVendor tells the query-builder to eager-load the nodes that are connected to
// the "vendor" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FilamentQuery) WithVendor(opts ...func(*VendorQuery)) *FilamentQuery {
	query := (&VendorClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withVendor = query
	return fq
}

// WithSpools tells the query-builder to eager-load the nodes that are connected to
// the "spools" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FilamentQuery) WithSpools(opts ...func(*SpoolQuery)) *FilamentQuery {
	query := (&SpoolClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withSpools = query
	return fq
}

// WithExtra tells the query-builder to eager-load the nodes that are connected to
// the "extra" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FilamentQuery) WithExtra(opts ...func(*FilamentFieldQuery)) *FilamentQuery {
	query := (&FilamentFieldClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withExtra = query
	return fq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Registered time.Time `json:"registered,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Filament.Query().
//		GroupBy(filament.FieldRegistered).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fq *FilamentQuery) GroupBy(field string, fields ...string) *FilamentGroupBy {
	fq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FilamentGroupBy{build: fq}
	grbuild.flds = &fq.ctx.Fields
	grbuild.label = filament.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Registered time.Time `json:"registered,omitempty"`
//	}
//
//	client.Filament.Query().
//		Select(filament.FieldRegistered).
//		Scan(ctx, &v)
func (fq *FilamentQuery) Select(fields ...string) *FilamentSelect {
	fq.ctx.Fields = append(fq.ctx.Fields, fields...)
	sbuild := &FilamentSelect{FilamentQuery: fq}
	sbuild.label = filament.Label
	sbuild.flds, sbuild.scan = &fq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FilamentSelect configured with the given aggregations.
func (fq *FilamentQuery) Aggregate(fns ...AggregateFunc) *FilamentSelect {
	return fq.Select().Aggregate(fns...)
}

func (fq *FilamentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fq); err != nil {
				return err
			}
		}
	}
	for _, f := range fq.ctx.Fields {
		if !filament.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fq.path != nil {
		prev, err := fq.path(ctx)
		if err != nil {
			return err
		}
		fq.sql = prev
	}
	return nil
}

func (fq *FilamentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Filament, error) {
	var (
		nodes       = []*Filament{}
		_spec       = fq.querySpec()
		loadedTypes = [3]bool{
			fq.withVendor != nil,
			fq.withSpools != nil,
			fq.withExtra != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Filament).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Filament{config: fq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fq.withVendor; query != nil {
		if err := fq.loadVendor(ctx, query, nodes, nil,
			func(n *Filament, e *Vendor) { n.Edges.Vendor = e }); err != nil {
			return nil, err
		}
	}
	if query := fq.withSpools; query != nil {
		if err := fq.loadSpools(ctx, query, nodes,
			func(n *Filament) { n.Edges.Spools = []*Spool{} },
			func(n *Filament, e *Spool) { n.Edges.Spools = append(n.Edges.Spools, e) }); err != nil {
			return nil, err
		}
	}
	if query := fq.withExtra; query != nil {
		if err := fq.loadExtra(ctx, query, nodes,
			func(n *Filament) { n.Edges.Extra = []*FilamentField{} },
			func(n *Filament, e *FilamentField) { n.Edges.Extra = append(n.Edges.Extra, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fq *FilamentQuery) loadVendor(ctx context.Context, query *VendorQuery, nodes []*Filament, init func(*Filament), assign func(*Filament, *Vendor)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Filament)
	for i := range nodes {
		fk := nodes[i].VendorID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(vendor.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "vendor_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (fq *FilamentQuery) loadSpools(ctx context.Context, query *SpoolQuery, nodes []*Filament, init func(*Filament), assign func(*Filament, *Spool)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Filament)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(spool.FieldFilamentID)
	}
	query.Where(predicate.Spool(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(filament.SpoolsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FilamentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "filament_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (fq *FilamentQuery) loadExtra(ctx context.Context, query *FilamentFieldQuery, nodes []*Filament, init func(*Filament), assign func(*Filament, *FilamentField)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Filament)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(filamentfield.FieldFilamentID)
	}
	query.Where(predicate.FilamentField(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(filament.ExtraColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FilamentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "filament_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (fq *FilamentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fq.querySpec()
	_spec.Node.Columns = fq.ctx.Fields
	if len(fq.ctx.Fields) > 0 {
		_spec.Unique = fq.ctx.Unique != nil && *fq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fq.driver, _spec)
}

func (fq *FilamentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(filament.Table, filament.Columns, sqlgraph.NewFieldSpec(filament.FieldID, field.TypeInt))
	_spec.From = fq.sql
	if unique := fq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fq.path != nil {
		_spec.Unique = true
	}
	if fields := fq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, filament.FieldID)
		for i := range fields {
			if fields[i] != filament.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if fq.withVendor != nil {
			_spec.Node.AddColumnOnce(filament.FieldVendorID)
		}
	}
	if ps := fq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fq *FilamentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fq.driver.Dialect())
	t1 := builder.Table(filament.Table)
	columns := fq.ctx.Fields
	if len(columns) == 0 {
		columns = filament.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fq.sql != nil {
		selector = fq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fq.ctx.Unique != nil && *fq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fq.predicates {
		p(selector)
	}
	for _, p := range fq.order {
		p(selector)
	}
	if offset := fq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FilamentGroupBy is the group-by builder for Filament entities.
type FilamentGroupBy struct {
	selector
	build *FilamentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fgb *FilamentGroupBy) Aggregate(fns ...AggregateFunc) *FilamentGroupBy {
	fgb.fns = append(fgb.fns, fns...)
	return fgb
}

// Scan applies the selector query and scans the result into the given value.
func (fgb *FilamentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fgb.build.ctx, ent.OpQueryGroupBy)
	if err := fgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FilamentQuery, *FilamentGroupBy](ctx, fgb.build, fgb, fgb.build.inters, v)
}

func (fgb *FilamentGroupBy) sqlScan(ctx context.Context, root *FilamentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fgb.fns))
	for _, fn := range fgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fgb.flds)+len(fgb.fns))
		for _, f := range *fgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FilamentSelect is the builder for selecting fields of Filament entities.
type FilamentSelect struct {
	*FilamentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fs *FilamentSelect) Aggregate(fns ...AggregateFunc) *FilamentSelect {
	fs.fns = append(fs.fns, fns...)
	return fs
}

// Scan applies the selector query and scans the result into the given value.
func (fs *FilamentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fs.ctx, ent.OpQuerySelect)
	if err := fs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FilamentQuery, *FilamentSelect](ctx, fs.FilamentQuery, fs, fs.inters, v)
}

func (fs *FilamentSelect) sqlScan(ctx context.Context, root *FilamentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fs.fns))
	for _, fn := range fs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
