// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"spoolman-go/ent/filament"
	"spoolman-go/ent/spoolvendor"
	"spoolman-go/ent/vendorfield"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SpoolVendorCreate is the builder for creating a SpoolVendor entity.
type SpoolVendorCreate struct {
	config
	mutation *SpoolVendorMutation
	hooks    []Hook
}

// SetRegistered sets the "registered" field.
func (svc *SpoolVendorCreate) SetRegistered(t time.Time) *SpoolVendorCreate {
	svc.mutation.SetRegistered(t)
	return svc
}

// SetName sets the "name" field.
func (svc *SpoolVendorCreate) SetName(s string) *SpoolVendorCreate {
	svc.mutation.SetName(s)
	return svc
}

// SetEmptySpoolWeight sets the "empty_spool_weight" field.
func (svc *SpoolVendorCreate) SetEmptySpoolWeight(f float32) *SpoolVendorCreate {
	svc.mutation.SetEmptySpoolWeight(f)
	return svc
}

// SetNillableEmptySpoolWeight sets the "empty_spool_weight" field if the given value is not nil.
func (svc *SpoolVendorCreate) SetNillableEmptySpoolWeight(f *float32) *SpoolVendorCreate {
	if f != nil {
		svc.SetEmptySpoolWeight(*f)
	}
	return svc
}

// SetComment sets the "comment" field.
func (svc *SpoolVendorCreate) SetComment(s string) *SpoolVendorCreate {
	svc.mutation.SetComment(s)
	return svc
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (svc *SpoolVendorCreate) SetNillableComment(s *string) *SpoolVendorCreate {
	if s != nil {
		svc.SetComment(*s)
	}
	return svc
}

// SetExternalID sets the "external_id" field.
func (svc *SpoolVendorCreate) SetExternalID(s string) *SpoolVendorCreate {
	svc.mutation.SetExternalID(s)
	return svc
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (svc *SpoolVendorCreate) SetNillableExternalID(s *string) *SpoolVendorCreate {
	if s != nil {
		svc.SetExternalID(*s)
	}
	return svc
}

// SetID sets the "id" field.
func (svc *SpoolVendorCreate) SetID(i int) *SpoolVendorCreate {
	svc.mutation.SetID(i)
	return svc
}

// AddFilamentIDs adds the "filaments" edge to the Filament entity by IDs.
func (svc *SpoolVendorCreate) AddFilamentIDs(ids ...int) *SpoolVendorCreate {
	svc.mutation.AddFilamentIDs(ids...)
	return svc
}

// AddFilaments adds the "filaments" edges to the Filament entity.
func (svc *SpoolVendorCreate) AddFilaments(f ...*Filament) *SpoolVendorCreate {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return svc.AddFilamentIDs(ids...)
}

// AddExtraIDs adds the "extra" edge to the VendorField entity by IDs.
func (svc *SpoolVendorCreate) AddExtraIDs(ids ...int) *SpoolVendorCreate {
	svc.mutation.AddExtraIDs(ids...)
	return svc
}

// AddExtra adds the "extra" edges to the VendorField entity.
func (svc *SpoolVendorCreate) AddExtra(v ...*VendorField) *SpoolVendorCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return svc.AddExtraIDs(ids...)
}

// Mutation returns the SpoolVendorMutation object of the builder.
func (svc *SpoolVendorCreate) Mutation() *SpoolVendorMutation {
	return svc.mutation
}

// Save creates the SpoolVendor in the database.
func (svc *SpoolVendorCreate) Save(ctx context.Context) (*SpoolVendor, error) {
	return withHooks(ctx, svc.sqlSave, svc.mutation, svc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (svc *SpoolVendorCreate) SaveX(ctx context.Context) *SpoolVendor {
	v, err := svc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (svc *SpoolVendorCreate) Exec(ctx context.Context) error {
	_, err := svc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (svc *SpoolVendorCreate) ExecX(ctx context.Context) {
	if err := svc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (svc *SpoolVendorCreate) check() error {
	if _, ok := svc.mutation.Registered(); !ok {
		return &ValidationError{Name: "registered", err: errors.New(`ent: missing required field "SpoolVendor.registered"`)}
	}
	if _, ok := svc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SpoolVendor.name"`)}
	}
	if v, ok := svc.mutation.Name(); ok {
		if err := spoolvendor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SpoolVendor.name": %w`, err)}
		}
	}
	if v, ok := svc.mutation.Comment(); ok {
		if err := spoolvendor.CommentValidator(v); err != nil {
			return &ValidationError{Name: "comment", err: fmt.Errorf(`ent: validator failed for field "SpoolVendor.comment": %w`, err)}
		}
	}
	if v, ok := svc.mutation.ExternalID(); ok {
		if err := spoolvendor.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "SpoolVendor.external_id": %w`, err)}
		}
	}
	if v, ok := svc.mutation.ID(); ok {
		if err := spoolvendor.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SpoolVendor.id": %w`, err)}
		}
	}
	return nil
}

func (svc *SpoolVendorCreate) sqlSave(ctx context.Context) (*SpoolVendor, error) {
	if err := svc.check(); err != nil {
		return nil, err
	}
	_node, _spec := svc.createSpec()
	if err := sqlgraph.CreateNode(ctx, svc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	svc.mutation.id = &_node.ID
	svc.mutation.done = true
	return _node, nil
}

func (svc *SpoolVendorCreate) createSpec() (*SpoolVendor, *sqlgraph.CreateSpec) {
	var (
		_node = &SpoolVendor{config: svc.config}
		_spec = sqlgraph.NewCreateSpec(spoolvendor.Table, sqlgraph.NewFieldSpec(spoolvendor.FieldID, field.TypeInt))
	)
	if id, ok := svc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := svc.mutation.Registered(); ok {
		_spec.SetField(spoolvendor.FieldRegistered, field.TypeTime, value)
		_node.Registered = value
	}
	if value, ok := svc.mutation.Name(); ok {
		_spec.SetField(spoolvendor.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := svc.mutation.EmptySpoolWeight(); ok {
		_spec.SetField(spoolvendor.FieldEmptySpoolWeight, field.TypeFloat32, value)
		_node.EmptySpoolWeight = value
	}
	if value, ok := svc.mutation.Comment(); ok {
		_spec.SetField(spoolvendor.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := svc.mutation.ExternalID(); ok {
		_spec.SetField(spoolvendor.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if nodes := svc.mutation.FilamentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   spoolvendor.FilamentsTable,
			Columns: []string{spoolvendor.FilamentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filament.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := svc.mutation.ExtraIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   spoolvendor.ExtraTable,
			Columns: []string{spoolvendor.ExtraColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vendorfield.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SpoolVendorCreateBulk is the builder for creating many SpoolVendor entities in bulk.
type SpoolVendorCreateBulk struct {
	config
	err      error
	builders []*SpoolVendorCreate
}

// Save creates the SpoolVendor entities in the database.
func (svcb *SpoolVendorCreateBulk) Save(ctx context.Context) ([]*SpoolVendor, error) {
	if svcb.err != nil {
		return nil, svcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(svcb.builders))
	nodes := make([]*SpoolVendor, len(svcb.builders))
	mutators := make([]Mutator, len(svcb.builders))
	for i := range svcb.builders {
		func(i int, root context.Context) {
			builder := svcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SpoolVendorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, svcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, svcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, svcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (svcb *SpoolVendorCreateBulk) SaveX(ctx context.Context) []*SpoolVendor {
	v, err := svcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (svcb *SpoolVendorCreateBulk) Exec(ctx context.Context) error {
	_, err := svcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (svcb *SpoolVendorCreateBulk) ExecX(ctx context.Context) {
	if err := svcb.Exec(ctx); err != nil {
		panic(err)
	}
}
