// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"spoolman-go/ent/predicate"
	"spoolman-go/ent/spoolfield"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SpoolFieldDelete is the builder for deleting a SpoolField entity.
type SpoolFieldDelete struct {
	config
	hooks    []Hook
	mutation *SpoolFieldMutation
}

// Where appends a list predicates to the SpoolFieldDelete builder.
func (sfd *SpoolFieldDelete) Where(ps ...predicate.SpoolField) *SpoolFieldDelete {
	sfd.mutation.Where(ps...)
	return sfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sfd *SpoolFieldDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sfd.sqlExec, sfd.mutation, sfd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sfd *SpoolFieldDelete) ExecX(ctx context.Context) int {
	n, err := sfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sfd *SpoolFieldDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(spoolfield.Table, sqlgraph.NewFieldSpec(spoolfield.FieldID, field.TypeInt))
	if ps := sfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sfd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sfd.mutation.done = true
	return affected, err
}

// SpoolFieldDeleteOne is the builder for deleting a single SpoolField entity.
type SpoolFieldDeleteOne struct {
	sfd *SpoolFieldDelete
}

// Where appends a list predicates to the SpoolFieldDelete builder.
func (sfdo *SpoolFieldDeleteOne) Where(ps ...predicate.SpoolField) *SpoolFieldDeleteOne {
	sfdo.sfd.mutation.Where(ps...)
	return sfdo
}

// Exec executes the deletion query.
func (sfdo *SpoolFieldDeleteOne) Exec(ctx context.Context) error {
	n, err := sfdo.sfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{spoolfield.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sfdo *SpoolFieldDeleteOne) ExecX(ctx context.Context) {
	if err := sfdo.Exec(ctx); err != nil {
		panic(err)
	}
}
