// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"spoolman-go/ent/filament"
	"spoolman-go/ent/predicate"
	"spoolman-go/ent/spoolvendor"
	"spoolman-go/ent/vendorfield"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SpoolVendorQuery is the builder for querying SpoolVendor entities.
type SpoolVendorQuery struct {
	config
	ctx           *QueryContext
	order         []spoolvendor.OrderOption
	inters        []Interceptor
	predicates    []predicate.SpoolVendor
	withFilaments *FilamentQuery
	withExtra     *VendorFieldQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SpoolVendorQuery builder.
func (svq *SpoolVendorQuery) Where(ps ...predicate.SpoolVendor) *SpoolVendorQuery {
	svq.predicates = append(svq.predicates, ps...)
	return svq
}

// Limit the number of records to be returned by this query.
func (svq *SpoolVendorQuery) Limit(limit int) *SpoolVendorQuery {
	svq.ctx.Limit = &limit
	return svq
}

// Offset to start from.
func (svq *SpoolVendorQuery) Offset(offset int) *SpoolVendorQuery {
	svq.ctx.Offset = &offset
	return svq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (svq *SpoolVendorQuery) Unique(unique bool) *SpoolVendorQuery {
	svq.ctx.Unique = &unique
	return svq
}

// Order specifies how the records should be ordered.
func (svq *SpoolVendorQuery) Order(o ...spoolvendor.OrderOption) *SpoolVendorQuery {
	svq.order = append(svq.order, o...)
	return svq
}

// QueryFilaments chains the current query on the "filaments" edge.
func (svq *SpoolVendorQuery) QueryFilaments() *FilamentQuery {
	query := (&FilamentClient{config: svq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := svq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := svq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(spoolvendor.Table, spoolvendor.FieldID, selector),
			sqlgraph.To(filament.Table, filament.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, spoolvendor.FilamentsTable, spoolvendor.FilamentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(svq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExtra chains the current query on the "extra" edge.
func (svq *SpoolVendorQuery) QueryExtra() *VendorFieldQuery {
	query := (&VendorFieldClient{config: svq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := svq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := svq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(spoolvendor.Table, spoolvendor.FieldID, selector),
			sqlgraph.To(vendorfield.Table, vendorfield.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, spoolvendor.ExtraTable, spoolvendor.ExtraColumn),
		)
		fromU = sqlgraph.SetNeighbors(svq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SpoolVendor entity from the query.
// Returns a *NotFoundError when no SpoolVendor was found.
func (svq *SpoolVendorQuery) First(ctx context.Context) (*SpoolVendor, error) {
	nodes, err := svq.Limit(1).All(setContextOp(ctx, svq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{spoolvendor.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (svq *SpoolVendorQuery) FirstX(ctx context.Context) *SpoolVendor {
	node, err := svq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SpoolVendor ID from the query.
// Returns a *NotFoundError when no SpoolVendor ID was found.
func (svq *SpoolVendorQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = svq.Limit(1).IDs(setContextOp(ctx, svq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{spoolvendor.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (svq *SpoolVendorQuery) FirstIDX(ctx context.Context) int {
	id, err := svq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SpoolVendor entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SpoolVendor entity is found.
// Returns a *NotFoundError when no SpoolVendor entities are found.
func (svq *SpoolVendorQuery) Only(ctx context.Context) (*SpoolVendor, error) {
	nodes, err := svq.Limit(2).All(setContextOp(ctx, svq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{spoolvendor.Label}
	default:
		return nil, &NotSingularError{spoolvendor.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (svq *SpoolVendorQuery) OnlyX(ctx context.Context) *SpoolVendor {
	node, err := svq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SpoolVendor ID in the query.
// Returns a *NotSingularError when more than one SpoolVendor ID is found.
// Returns a *NotFoundError when no entities are found.
func (svq *SpoolVendorQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = svq.Limit(2).IDs(setContextOp(ctx, svq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{spoolvendor.Label}
	default:
		err = &NotSingularError{spoolvendor.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (svq *SpoolVendorQuery) OnlyIDX(ctx context.Context) int {
	id, err := svq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SpoolVendors.
func (svq *SpoolVendorQuery) All(ctx context.Context) ([]*SpoolVendor, error) {
	ctx = setContextOp(ctx, svq.ctx, ent.OpQueryAll)
	if err := svq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SpoolVendor, *SpoolVendorQuery]()
	return withInterceptors[[]*SpoolVendor](ctx, svq, qr, svq.inters)
}

// AllX is like All, but panics if an error occurs.
func (svq *SpoolVendorQuery) AllX(ctx context.Context) []*SpoolVendor {
	nodes, err := svq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SpoolVendor IDs.
func (svq *SpoolVendorQuery) IDs(ctx context.Context) (ids []int, err error) {
	if svq.ctx.Unique == nil && svq.path != nil {
		svq.Unique(true)
	}
	ctx = setContextOp(ctx, svq.ctx, ent.OpQueryIDs)
	if err = svq.Select(spoolvendor.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (svq *SpoolVendorQuery) IDsX(ctx context.Context) []int {
	ids, err := svq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (svq *SpoolVendorQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, svq.ctx, ent.OpQueryCount)
	if err := svq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, svq, querierCount[*SpoolVendorQuery](), svq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (svq *SpoolVendorQuery) CountX(ctx context.Context) int {
	count, err := svq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (svq *SpoolVendorQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, svq.ctx, ent.OpQueryExist)
	switch _, err := svq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (svq *SpoolVendorQuery) ExistX(ctx context.Context) bool {
	exist, err := svq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SpoolVendorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (svq *SpoolVendorQuery) Clone() *SpoolVendorQuery {
	if svq == nil {
		return nil
	}
	return &SpoolVendorQuery{
		config:        svq.config,
		ctx:           svq.ctx.Clone(),
		order:         append([]spoolvendor.OrderOption{}, svq.order...),
		inters:        append([]Interceptor{}, svq.inters...),
		predicates:    append([]predicate.SpoolVendor{}, svq.predicates...),
		withFilaments: svq.withFilaments.Clone(),
		withExtra:     svq.withExtra.Clone(),
		// clone intermediate query.
		sql:  svq.sql.Clone(),
		path: svq.path,
	}
}

// WithFilaments tells the query-builder to eager-load the nodes that are connected to
// the "filaments" edge. The optional arguments are used to configure the query builder of the edge.
func (svq *SpoolVendorQuery) WithFilaments(opts ...func(*FilamentQuery)) *SpoolVendorQuery {
	query := (&FilamentClient{config: svq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	svq.withFilaments = query
	return svq
}

// WithExtra tells the query-builder to eager-load the nodes that are connected to
// the "extra" edge. The optional arguments are used to configure the query builder of the edge.
func (svq *SpoolVendorQuery) WithExtra(opts ...func(*VendorFieldQuery)) *SpoolVendorQuery {
	query := (&VendorFieldClient{config: svq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	svq.withExtra = query
	return svq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Registered time.Time `json:"registered,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SpoolVendor.Query().
//		GroupBy(spoolvendor.FieldRegistered).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (svq *SpoolVendorQuery) GroupBy(field string, fields ...string) *SpoolVendorGroupBy {
	svq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SpoolVendorGroupBy{build: svq}
	grbuild.flds = &svq.ctx.Fields
	grbuild.label = spoolvendor.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Registered time.Time `json:"registered,omitempty"`
//	}
//
//	client.SpoolVendor.Query().
//		Select(spoolvendor.FieldRegistered).
//		Scan(ctx, &v)
func (svq *SpoolVendorQuery) Select(fields ...string) *SpoolVendorSelect {
	svq.ctx.Fields = append(svq.ctx.Fields, fields...)
	sbuild := &SpoolVendorSelect{SpoolVendorQuery: svq}
	sbuild.label = spoolvendor.Label
	sbuild.flds, sbuild.scan = &svq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SpoolVendorSelect configured with the given aggregations.
func (svq *SpoolVendorQuery) Aggregate(fns ...AggregateFunc) *SpoolVendorSelect {
	return svq.Select().Aggregate(fns...)
}

func (svq *SpoolVendorQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range svq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, svq); err != nil {
				return err
			}
		}
	}
	for _, f := range svq.ctx.Fields {
		if !spoolvendor.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if svq.path != nil {
		prev, err := svq.path(ctx)
		if err != nil {
			return err
		}
		svq.sql = prev
	}
	return nil
}

func (svq *SpoolVendorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SpoolVendor, error) {
	var (
		nodes       = []*SpoolVendor{}
		_spec       = svq.querySpec()
		loadedTypes = [2]bool{
			svq.withFilaments != nil,
			svq.withExtra != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SpoolVendor).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SpoolVendor{config: svq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, svq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := svq.withFilaments; query != nil {
		if err := svq.loadFilaments(ctx, query, nodes,
			func(n *SpoolVendor) { n.Edges.Filaments = []*Filament{} },
			func(n *SpoolVendor, e *Filament) { n.Edges.Filaments = append(n.Edges.Filaments, e) }); err != nil {
			return nil, err
		}
	}
	if query := svq.withExtra; query != nil {
		if err := svq.loadExtra(ctx, query, nodes,
			func(n *SpoolVendor) { n.Edges.Extra = []*VendorField{} },
			func(n *SpoolVendor, e *VendorField) { n.Edges.Extra = append(n.Edges.Extra, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (svq *SpoolVendorQuery) loadFilaments(ctx context.Context, query *FilamentQuery, nodes []*SpoolVendor, init func(*SpoolVendor), assign func(*SpoolVendor, *Filament)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*SpoolVendor)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(filament.FieldVendorID)
	}
	query.Where(predicate.Filament(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(spoolvendor.FilamentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VendorID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "vendor_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (svq *SpoolVendorQuery) loadExtra(ctx context.Context, query *VendorFieldQuery, nodes []*SpoolVendor, init func(*SpoolVendor), assign func(*SpoolVendor, *VendorField)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*SpoolVendor)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(vendorfield.FieldVendorID)
	}
	query.Where(predicate.VendorField(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(spoolvendor.ExtraColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VendorID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "vendor_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (svq *SpoolVendorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := svq.querySpec()
	_spec.Node.Columns = svq.ctx.Fields
	if len(svq.ctx.Fields) > 0 {
		_spec.Unique = svq.ctx.Unique != nil && *svq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, svq.driver, _spec)
}

func (svq *SpoolVendorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(spoolvendor.Table, spoolvendor.Columns, sqlgraph.NewFieldSpec(spoolvendor.FieldID, field.TypeInt))
	_spec.From = svq.sql
	if unique := svq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if svq.path != nil {
		_spec.Unique = true
	}
	if fields := svq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, spoolvendor.FieldID)
		for i := range fields {
			if fields[i] != spoolvendor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := svq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := svq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := svq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := svq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (svq *SpoolVendorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(svq.driver.Dialect())
	t1 := builder.Table(spoolvendor.Table)
	columns := svq.ctx.Fields
	if len(columns) == 0 {
		columns = spoolvendor.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if svq.sql != nil {
		selector = svq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if svq.ctx.Unique != nil && *svq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range svq.predicates {
		p(selector)
	}
	for _, p := range svq.order {
		p(selector)
	}
	if offset := svq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := svq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SpoolVendorGroupBy is the group-by builder for SpoolVendor entities.
type SpoolVendorGroupBy struct {
	selector
	build *SpoolVendorQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (svgb *SpoolVendorGroupBy) Aggregate(fns ...AggregateFunc) *SpoolVendorGroupBy {
	svgb.fns = append(svgb.fns, fns...)
	return svgb
}

// Scan applies the selector query and scans the result into the given value.
func (svgb *SpoolVendorGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, svgb.build.ctx, ent.OpQueryGroupBy)
	if err := svgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SpoolVendorQuery, *SpoolVendorGroupBy](ctx, svgb.build, svgb, svgb.build.inters, v)
}

func (svgb *SpoolVendorGroupBy) sqlScan(ctx context.Context, root *SpoolVendorQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(svgb.fns))
	for _, fn := range svgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*svgb.flds)+len(svgb.fns))
		for _, f := range *svgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*svgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := svgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SpoolVendorSelect is the builder for selecting fields of SpoolVendor entities.
type SpoolVendorSelect struct {
	*SpoolVendorQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (svs *SpoolVendorSelect) Aggregate(fns ...AggregateFunc) *SpoolVendorSelect {
	svs.fns = append(svs.fns, fns...)
	return svs
}

// Scan applies the selector query and scans the result into the given value.
func (svs *SpoolVendorSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, svs.ctx, ent.OpQuerySelect)
	if err := svs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SpoolVendorQuery, *SpoolVendorSelect](ctx, svs.SpoolVendorQuery, svs, svs.inters, v)
}

func (svs *SpoolVendorSelect) sqlScan(ctx context.Context, root *SpoolVendorQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(svs.fns))
	for _, fn := range svs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*svs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := svs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
