// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"spoolman-go/ent/predicate"
	"spoolman-go/ent/spoolvendor"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SpoolVendorDelete is the builder for deleting a SpoolVendor entity.
type SpoolVendorDelete struct {
	config
	hooks    []Hook
	mutation *SpoolVendorMutation
}

// Where appends a list predicates to the SpoolVendorDelete builder.
func (svd *SpoolVendorDelete) Where(ps ...predicate.SpoolVendor) *SpoolVendorDelete {
	svd.mutation.Where(ps...)
	return svd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (svd *SpoolVendorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, svd.sqlExec, svd.mutation, svd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (svd *SpoolVendorDelete) ExecX(ctx context.Context) int {
	n, err := svd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (svd *SpoolVendorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(spoolvendor.Table, sqlgraph.NewFieldSpec(spoolvendor.FieldID, field.TypeInt))
	if ps := svd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, svd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	svd.mutation.done = true
	return affected, err
}

// SpoolVendorDeleteOne is the builder for deleting a single SpoolVendor entity.
type SpoolVendorDeleteOne struct {
	svd *SpoolVendorDelete
}

// Where appends a list predicates to the SpoolVendorDelete builder.
func (svdo *SpoolVendorDeleteOne) Where(ps ...predicate.SpoolVendor) *SpoolVendorDeleteOne {
	svdo.svd.mutation.Where(ps...)
	return svdo
}

// Exec executes the deletion query.
func (svdo *SpoolVendorDeleteOne) Exec(ctx context.Context) error {
	n, err := svdo.svd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{spoolvendor.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (svdo *SpoolVendorDeleteOne) ExecX(ctx context.Context) {
	if err := svdo.Exec(ctx); err != nil {
		panic(err)
	}
}
