// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Filament is the predicate function for filament builders.
type Filament func(*sql.Selector)

// FilamentField is the predicate function for filamentfield builders.
type FilamentField func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// Spool is the predicate function for spool builders.
type Spool func(*sql.Selector)

// SpoolField is the predicate function for spoolfield builders.
type SpoolField func(*sql.Selector)

// SpoolVendor is the predicate function for spoolvendor builders.
type SpoolVendor func(*sql.Selector)

// VendorField is the predicate function for vendorfield builders.
type VendorField func(*sql.Selector)
