// Code generated by ent, DO NOT EDIT.

package filamentfield

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the filamentfield type in the database.
	Label = "filament_field"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFilamentID holds the string denoting the filament_id field in the database.
	FieldFilamentID = "filament_id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// EdgeFilament holds the string denoting the filament edge name in mutations.
	EdgeFilament = "filament"
	// Table holds the table name of the filamentfield in the database.
	Table = "filament_fields"
	// FilamentTable is the table that holds the filament relation/edge.
	FilamentTable = "filament_fields"
	// FilamentInverseTable is the table name for the Filament entity.
	// It exists in this package in order to avoid circular dependency with the "filament" package.
	FilamentInverseTable = "filaments"
	// FilamentColumn is the table column denoting the filament relation/edge.
	FilamentColumn = "filament_id"
)

// Columns holds all SQL columns for filamentfield fields.
var Columns = []string{
	FieldID,
	FieldFilamentID,
	FieldKey,
	FieldValue,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
)

// OrderOption defines the ordering options for the FilamentField queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFilamentID orders the results by the filament_id field.
func ByFilamentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilamentID, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByFilamentField orders the results by filament field.
func ByFilamentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFilamentStep(), sql.OrderByField(field, opts...))
	}
}
func newFilamentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FilamentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FilamentTable, FilamentColumn),
	)
}
